spring.application.name=demo
# spring.data.mongodb.host=practiceculsture-shard-00-00.by3cz.mongodb.net
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=practice_sample

spring.data.mongodb.uri=mongodb+srv://17vishalnagar2002:acOblAzSQwlwtgOw@practiceculsture.by3cz.mongodb.net/?retryWrites=true&w=majority&appName=PracticeCulsture
spring.data.mongodb.database=jobapplication
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
